javascript
(function (translator) {
	translator.translations["tr"] = {
		// javascript alerts or messages
		"testneteditionactivated": "TEST AĞI SÜRÜMÜ AKTİF",
		"paperlabelbitcoinaddress": "Bitcoin Adresi:",
		"paperlabelprivatekey": "Özel Anahtar:",
		"paperlabelencryptedkey": "Şifrelenmiş Özel Anahtar (Parola gereklidir)",
		"bulkgeneratingaddresses": "Adresler oluşturuluyor... ",
		"brainalertpassphrasetooshort": "Girdiğiniz parola çok kısa.\n\n",
		"brainalertpassphrasewarning": "Uyarı: Güçlü bir parola seçmek, parolanızı bulmak ve Bitcoinlerinizi çalmak için yapılan bruteforce saldırılarından korunmak için önemlidir.",
		"brainalertpassphrasedoesnotmatch": "Parola, doğrulama parolasıyla eşleşmiyor.",
		"detailalertnotvalidprivatekey": "Girdiğiniz metin geçerli bir Özel Anahtar değil",
		"detailconfirmsha256": "Girdiğiniz metin geçerli bir Özel Anahtar değil!\n\nMetni bir parola olarak kullanıp bu parolanın SHA256 hash'i üzerinden bir Özel Anahtar oluşturmak istiyor musunuz?\n\nUyarı: Güçlü bir parola seçmek, parolanızı bulmak ve Bitcoinlerinizi çalmak için yapılan bruteforce saldırılarından korunmak için önemlidir.",
		"bip38alertincorrectpassphrase": "Bu şifrelenmiş özel anahtar için yanlış parola.",
		"bip38alertpassphraserequired": "BIP38 ile şifrelemek için parola gereklidir",
		"vanityinvalidinputcouldnotcombinekeys": "Geçersiz giriş. Anahtarlar birleştirilemedi.",
		"vanityalertinvalidinputpublickeysmatch": "Geçersiz giriş. İki girişin de genel anahtarı aynı. Farklı iki anahtar girmelisiniz.",
		"vanityalertinvalidinputcannotmultiple": "Geçersiz giriş. İki genel anahtarı çarpmak mümkün değil. Bir Bitcoin adresi elde etmek için iki genel anahtarı eklemek için 'Ekle' seçeneğini seçin.",
		"vanityprivatekeyonlyavailable": "Yalnızca iki özel anahtarı birleştirdiğinizde mevcuttur",
		"vanityalertinvalidinputprivatekeysmatch": "Geçersiz giriş. İki girişin de özel anahtarı aynı. Farklı iki anahtar girmelisiniz.",

		// header and menu html
		"tagline": "Çevrimdışı Bitcoin Cüzdanı Oluşturucu",
		"generatelabelbitcoinaddress": "Bitcoin adresi oluşturuluyor...",
		"generatelabelmovemouse": "ENTROPİ eklemek için MOUSE'u hareket ettirin...",
		"generatelabelkeypress": "VEYA beyaz kutuya rastgele karakterler girin",
		"singlewallet": "Tek Cüzdan",
		"paperwallet": "Kağıt Cüzdan",
		"bulkwallet": "Toplu Cüzdan",
		"brainwallet": "Beyin Cüzdanı",
		"vanitywallet": "Özel Adres Cüzdanı",
		"splitwallet": "Bölünmüş Cüzdan",
		"detailwallet": "Cüzdan Detayları",

		// footer html
		"footerlabeldonations": "Bağışlar:",
		"footerlabeltranslatedby": "Çeviri: 1Gy7NYSJNUYqUdXTBow5d7bCUEJkUFDFSq",
		"footerlabelpgp": "PGP",
		"footerlabelversion": "Sürüm Geçmişi",
		"footerlabelgithub": "GitHub Deposu",
		"footerlabelgithubzip": "zip",
		"footerlabelsig": "imza",
		"footerlabelcopyright1": "Telif hakkı bitaddress.org.",
		"footerlabelcopyright2": "JavaScript telif hakkı kodu içinde bulunmaktadır.",
		"footerlabelnowarranty": "Hiçbir garanti yoktur.",

		// status html
		"statuslabelcryptogood": "&#10004; İyi!",
		"statuslabelcryptogood1": "Tarayıcınız window.crypto.getRandomValues kullanarak kriptografik olarak rastgele anahtarlar oluşturabilir",
		"statusokcryptogood": "OK",
		"statuslabelcryptobad": "&times; Oh hayır!",
		"statuslabelcryptobad1": "Tarayıcınız window.crypto.getRandomValues'ı desteklemiyor. Üretilen anahtarların güvenliğini artırmak için daha modern bir tarayıcı kullanmalısınız.",
		"statusokcryptobad": "OK",
		"statuslabelunittestsgood": "&#10004; İyi!",
		"statuslabelunittestsgood1": "Tüm senkronizasyon birim testleri geçti.",
		"statusokunittestsgood": "OK",
		"statuslabelunittestsbad": "&times; Oh hayır!",
		"statuslabelunittestsbad1": "Bazı senkronizasyon birim testleri geçmedi. Bu üreteci kullanmak için başka bir tarayıcı bulmalısınız.",
		"statusokunittestsbad": "OK",
		"statuslabelprotocolgood": "&#10004; İyi!",
		"statuslabelprotocolgood1": "Bu üreteci yerel bilgisayarınızdan çalıştırıyorsunuz. <br />İpucu: Çevrimdışı olduğunuzu çift kontrol edin ",
		"statusokprotocolgood": "OK",
		"statuslabelprotocolbad": "&#9888; İki kez düşünün!",
		"statuslabelprotocolbad1": "Bu üreteci canlı bir web sitesinden çevrimiçi çalıştırıyor gibi görünüyorsunuz. Değerli cüz

danlar için,",
		"statuslabelprotocolbad2": "GitHub'dan zip dosyasını indirin ve bu üreteci yerel bir HTML dosyası olarak çevrimdışı çalıştırın.",
		"statuslabelprotocolbad3": "OK",
		"statusokprotocolbad": "OK",
		"statuslabelkeypool1": "Mevcut oturumunuz boyunca oluşturduğunuz tüm Bitcoin Adresleri ve Özel Anahtarların kaydıdır. Sayfayı yeniden yüklerseniz yeni bir oturum oluşturulur.",
		"statuskeypoolrefresh": "Yenile",
		"statusokkeypool": "OK",

		// single wallet html
		"newaddress": "Yeni Adres Oluştur",
		"singleprint": "Yazdır",
		"singlelabelbitcoinaddress": "Bitcoin Adresi:",
		"singlelabelprivatekey": "Özel Anahtar (Cüzdan İçe Aktarma Biçimi):",
		"singletip1": "Bir Bitcoin cüzdanı, biri Bitcoin adresine ve diğeri Bitcoin özel anahtarına karşılık gelen bir çift adres kadar basittir. Burada gösterilen cüzdan, kendi web tarayıcınızda sizin için oluşturulmuş ve bu yüzden yukarıda gösterilmiştir.",
		"singletip2": "Bu cüzdanı güvende tutmak için, onu yazdırmalısınız veya alternatif olarak alıcı Bitcoin adresini ve özel anahtarı kaydetmelisiniz. Özel anahtarın bir yedek kopyasını oluşturmak ve güvenli bir yerde saklamak önemlidir. Bu site, özel anahtarınızın önceden belirlenmiş bir kopyası veya yedeği bulundurmaz. PGP'ye aşina iseniz, HTML sayfasının tamamını indirebilir ve böylece sayfanızın site yazarından geldiğini doğrulayabilirsiniz, kaydedilmiş HTML sayfanızın SHA1 hash'ini bu sitenin altındaki doğrulanmış tarihli sürümle karşılaştırarak. Bu siteyi terk ederseniz veya yenilerseniz veya 'Yeni bir adres oluştur' a basarsanız ... o zaman yeni bir özel anahtar oluşturulur ve önceki özel anahtar artık bulunamaz hale gelir. Bitcoin özel anahtarınız gizli tutulmalıdır. Kim özel anahtarı biliyorsa, biriktirdiğiniz tüm Bitcoin'leri ve alıcı adresle ilişkilendirilen Bitcoin'leri boşaltma yeteneğine sahip olur. Cüzdanı yazdırıyorsanız, su geçirmez bir çanta içinde suya dayanıklı bir yere koyduğunuzdan emin olun. Kağıt cüzdanı, nakit para ve banknotlar gibi işlem yapın.",
		"singletip3": "Cüzdanınıza fon eklemek için, Bitcoin'leri alıcı adresinize gönderilmesini istediğiniz yeri belirtin.",
		"singletip4": "Cüzdanınızın içeriğini kontrol ederek blockchain.info veya blockexplorer.com'a gidin ve Bitcoin alıcı adresinizi yazarak kontrol edin.",
		"singletip5": "Bitcoin'leri harcamak için, blockchain.info'ya gidin ve Bitcoin adresinizden tüm fonları bu sitenin hesabına aktarın. Ayrıca, popüler bir P2P bitcoin programını indirip özel anahtarınızı bir P2P cüzdanına aktararak fonlarınızı harcayabilirsiniz. Özel anahtarınızı P2P bitcoin programına aktardığınızda ve fonlarınızı harcadığınızda, özel anahtarınız P2P cüzdanındaki diğer özel anahtarlarla birlikte entegre edilecektir. Bir işlem gerçekleştirdiğinizde, değişim, P2P cüzdanı içindeki başka bir Bitcoin adresine gönderilir. Bu nedenle, P2P cüzdanını yedeklemeniz ve güvende tutmanız gerekmektedir, çünkü kalan tüm Bitcoinler orada saklanır. Satoshi, bir cüzdanı asla silmemeniz gerektiği konusunda uyardı.",
		"singleshare": "PAYLAŞ",
		"singlesecret": "GİZLİ",

		// paper wallet html
		"paperlabelhideart": "Resmi Gizle?",
		"paperlabeladdressesperpage": "Sayfa başına adres:",
		"paperlabeladdressestogenerate": "Oluşturulacak adres sayısı:",
		"papergenerate": "Oluştur",
		"paperprint": "Yazdır",
		"paperlabelBIPpassphrase": "Parola:",
		"paperlabelencrypt": "BIP38 ile Şifrele?",

		// bulk wallet html
		"bulklabelstartindex": "Başlangıç dizini:",
		"bulklabelrowstogenerate": "Oluşturulacak satırlar:",
		"bulklabelcompressed": "Sıkıştırılmış adresler?",
		"bulkgenerate": "Oluştur",
		"bulkprint": "Yazdır",
		"bulklabelcsv": "Virgülle Ayrılmış Değerler (CSV):",
		"bulklabelformat": "Dizin,Adres,Özel Anahtar (WIF)",
		"bulklabelq1": "Neden web sitemde Bitcoin kabul etmek için Toplu Cüzdan kullanmalıyım?",
		"bulka1": "Web sitenizde Bitcoin kabul etmek için geleneksel yaklaşım, resmi Bitcoin yazılımını (\"bitcoind\") kurmayı gerektirir. Birçok barındırıcı, resmi Bitcoin yazılımının kurulumunu desteklemez. Ayrıca, web sunucunuzda Bitcoin yazılımını çalıştırmak, özel anahtarlarınızın sunucuda barındırılması anlamına gelir ve bu nedenle web sunucunuzun tehlikeye girmesi durumunda çal

ınabilir. Toplu cüzdan kullanarak, yalnızca Bitcoin adreslerini sunucunuza yayınlamanız ve özel anahtarları değil, yani sunucunuzun tehlikeye girmesi durumunda cüzdanınızın çalınma riski olmaz.",
		"bulklabelq2": "Web sitemde Bitcoin kullanmak için Toplu Cüzdanı nasıl kullanabilirim?",
		"bulklabela2li1": "Toplu Cüzdanı kullanarak, büyük miktarda Bitcoin adresi (10.000+) önceden oluşturabilirsiniz. Virgülle ayrılmış verileri (CSV) bilgisayarınızdaki güvenli bir metin dosyasına kopyalayın. Bu dosyayı güvenli bir yerde saklayın.",
		"bulklabela2li2": "Bitcoin adreslerini web sunucunuzdaki bir veritabanına içe aktarın. (Web sunucunuza cüzdan veya özel anahtarları eklemeğin, sunucunuzun tehlikeye girmesi durumunda çalınma riski vardır. Ziyaretçilerinizin görebileceği yalnızca Bitcoin adreslerini ekleyin.)",
		"bulklabela2li3": "Çevrimiçi alışveriş sepetinizde, müşterilerinizin size Bitcoin ile ödeme yapmasını sağlamak için bir seçenek ekleyin. Bir müşteri Bitcoin ile ödeme yapmayı seçtiğinde, siparişleriyle ilişkilendirilecek bir \"ödeme adresi\" olarak veritabanınızdaki bir adresi gösterebilir ve bu adresi siparişleriyle birlikte kaydedebilirsiniz.",
		"bulklabela2li4": "Ödemenin alındığı konusunda bilgilendirilmelisiniz. Google'da \"bitcoin ödeme bildirimi\" arayın ve bir Bitcoin ödeme bildirim servisine kaydolun. Web hizmetleri, API'ler, SMS, e-posta vb. aracılığıyla sizi uyaracak birçok hizmet vardır. Otomatik olarak programlanmış bildirim aldıktan sonra müşteri siparişini işleyebilirsiniz. Bir ödemenin gelip gelmediğini el ile kontrol etmek için Block Explorer'ı kullanabilirsiniz. ADRES'i kontrol etmek istediğiniz Bitcoin adresiyle değiştirin. İşlemin onaylanması 10 ila 60 dakika sürebilir.<br />http://www.blockexplorer.com/address/ADRES<br /><br />Onaylanmamış işlemleri buradan görüntüleyebilirsiniz: http://blockchain.info/ <br />İşlemi 30 saniye içinde görmelisiniz.",
		"bulklabela2li5": "Bitcoin'leriniz blok zincirinde güvenli bir şekilde birikecektir. Adım 1'de oluşturduğunuz orijinal cüzdanı kullanarak harcamalarınızı yapın.",

		// brain wallet html
		"brainlabelenterpassphrase": "Parolanızı girin: ",
		"brainlabelshow": "Göster?",
		"brainprint": "Yazdır",
		"brainlabelconfirm": "Parolayı onayla: ",
		"brainview": "Görüntüle",
		"brainalgorithm": "Algoritma: SHA256(parola)",
		"brainlabelbitcoinaddress": "Bitcoin Adresi:",
		"brainlabelprivatekey": "Özel Anahtar (Cüzdan İçe Aktarma Biçimi):",

		// vanity wallet html
		"vanitylabelstep1": "Adım 1 - \"Adım 1 Anahtar Çiftini\" Oluştur",
		"vanitynewkeypair": "Oluştur",
		"vanitylabelstep1publickey": "Adım 1 Halka Açık Anahtar:",
		"vanitylabelstep1pubnotes": "Bunu Vanity Pool sitesindeki Your-Public-Key kutusuna kopyalayın.",
		"vanitylabelstep1privatekey": "Adım 1 Özel Anahtar:",
		"vanitylabelstep1privnotes": "Bu Özel Anahtarı bir metin dosyasına kopyalayın. İdeal olarak, bunu şifreli bir dosyada saklayın. Vanity Pool, ön ekini bulduğunda bu Özel Anahtarı geri almanız gerekecek.",
		"vanitylabelstep2calculateyourvanitywallet": "Adım 2 - Vanity Cüzdanınızı Hesaplayın",
		"vanitylabelenteryourpart": "Özel Anahtarı girin (yukarıda oluşturulan ve daha önce kaydedilen):",
		"vanitylabelenteryourpoolpart": "Özel Anahtarı girin (Vanity Pool'dan):",
		"vanitylabelnote1": "[NOT: Bu kutu bir halka açık anahtar veya özel anahtar alabilir]",
		"vanitylabelnote2": "[NOT: Bu kutu bir halka açık anahtar veya özel anahtar alabilir]",
		"vanitylabelradioadd": "Ekle",
		"vanitylabelradiomultiply": "Çarp",
		"vanitycalc": "Vanity Cüzdanını Hesapla",
		"vanitylabelbitcoinaddress": "Vanity Bitcoin Adresi:",
		"vanitylabelnotesbitcoinaddress": "Yukarıdaki, gereken ön eki içeren yeni adresinizdir.",
		"vanitylabelpublickeyhex": "Vanity Halka Açık Anahtar (HEX):",
		"vanitylabelnotespublickeyhex": "Bu, onaltılık formatında Halka Açık Anahtardır. ",
		"vanitylabelprivatekey": "Vanity Özel Anahtar (WIF):",
		"vanitylabelnotesprivatekey": "Bu, cüzdanınıza erişmek için Özel Anahtardır. ",

		// detail wallet html
		"detaillabelenterprivatekey": "Özel Anahtarı Girin",
		"detailkeyformats": "Anahtar Biçimleri: WIF, WIFC, HEX, B64, B6, MINI, BIP38",
		"detailview": "Ayrıntı

ları Göster",
		"detailprint": "Yazdır",
		"detaillabelnote1": "Bitcoin Özel Anahtarınızı gizli tutun. Anahtarın bilgisayarınıza girildiğinden ve internete bağlı olmadığından emin olun.",
		"detaillabelnote2": "Kağıt cüzdan veya yazılım cüzdanı gibi güvende saklayın.",
		"detaillabelbitcoinaddress": "Bitcoin Adresi:",
		"detaillabelbitcoinaddresscomp": "Bitcoin Adresi (Sıkıştırılmış):",
		"detaillabelpublickey": "Halka Açık Anahtar (Hex):",
		"detaillabelprivatekey": "Özel Anahtar (WIF & WIFC):",
		"detaillabelprivatekeyhex": "Özel Anahtar (Hex):",
		"detaillabelprivwif": "Özel Anahtar (WIF):",
		"detaillabelprivwifcomp": "Özel Anahtar (WIF Sıkıştırılmış):",
		"detailwifprefix": "'5' veya 'K' veya 'L'",
		"detailcompwifprefix": "'K' veya 'L'",
		"detaillabelprivhex": "Özel Anahtar (Hex):",
		"detaillabelq1": "Nasıl bir Özel Anahtar kullanırım?",
		"detaila1": "Bitcoin cüzdanlarının birkaç farklı biçimi vardır, ancak en yaygın kullanılanı WIF (Wallet Import/Export Format) olarak adlandırılır. Bu format, özel anahtarları yazı biçiminde ifade eder, böylece kolayca metin olarak yazılabilir. ",
		"detaillabelq2": "Özel Anahtarımı nasıl saklarım?",
		"detaila2": "Özel anahtarlarınızı güvende tutmanın birkaç yolu vardır. Kağıt cüzdan gibi fiziksel bir depolama cihazında saklamak en güvenli yöntemlerden biridir. Özel anahtarlarınızı şifreleyerek dijital olarak saklamak da güvenli bir seçenektir, ancak unutulmaması veya kaybolmaması için güçlü bir şifre kullanmalısınız.",
		"detaillabelq3": "WIF nedir?",
		"detaila3": "WIF (Wallet Import/Export Format), özel anahtarları yazı biçiminde ifade etmek için kullanılan bir formattır. Bu format, özel anahtarları insanların okuyabileceği ve yazabileceği bir formata dönüştürür. Bitcoin cüzdanlarının çoğu, bu formatı özel anahtarları depolamak için kullanır.",
		"detaillabelq4": "WIFC nedir?",
		"detaila4": "WIFC, sıkıştırılmış WIF'yi (Wallet Import/Export Format) temsil eder. Bu form, WIF'ye benzer, ancak daha kısa bir şekle sahiptir, böylece daha az yer kaplar. Cüzdanlar ve diğer Bitcoin yazılımları, bu formu özel anahtarları depolamak için kullanır.",
		"detaillabelq5": "Hexadecimal nedir?",
		"detaila5": "Hexadecimal, 16'lık sayma sistemini ifade etmek için kullanılan bir sayı sistemidir. Bitcoin özel anahtarlarının birçok biçimi hexadecimal olarak temsil edilir, çünkü bu biçim bilgisayarlar tarafından işlem yapmak için daha uygun ve verimlidir.",
		"detaillabelq6": "BIP38 nedir?",
		"detaila6": "BIP38, özel anahtarları şifrelemek için kullanılan bir şifreleme protokolüdür. Bu, özel anahtarları güvende tutmak için ek bir katman sağlar, çünkü şifrelenmiş bir anahtar, sadece doğru parolayı bilen kişi tarafından çözülebilir. BIP38 kullanarak, özel anahtarınızı yedeklemek ve güvende tutmak daha güvenli hale gelir.",
	};
})(localization);
